# Generated by Django 3.0.4 on 2020-03-06 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200306_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='Key_result_1',
            field=models.CharField(default='Write here', max_length=200),
        ),
        migrations.AlterField(
            model_name='form',
            name='Key_result_2',
            field=models.CharField(default='Write here', max_length=200),
        ),
        migrations.AlterField(
            model_name='form',
            name='Key_result_3',
            field=models.CharField(default='Write here', max_length=200),
        ),
        migrations.AlterField(
            model_name='form',
            name='Key_result_4',
            field=models.CharField(default='Write here', max_length=200),
        ),
        migrations.AlterField(
            model_name='form',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 6, 12, 41, 38, 613600), verbose_name='published date'),
        ),
        migrations.AlterField(
            model_name='site',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 6, 12, 41, 38, 612603), verbose_name='published date'),
        ),
    ]
