# Generated by Django 3.0.4 on 2020-03-06 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200306_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 6, 11, 45, 27, 119143), verbose_name='published date'),
        ),
    ]
