# Generated by Django 3.0.4 on 2020-03-06 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200306_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'verbose_name_plural': 'Forms'},
        ),
        migrations.AddField(
            model_name='form',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 6, 12, 32, 9, 235730), verbose_name='published date'),
        ),
        migrations.AddField(
            model_name='form',
            name='des',
            field=models.TextField(default='Write here'),
        ),
        migrations.AddField(
            model_name='form',
            name='for_whom',
            field=models.CharField(default='Write here', max_length=200),
        ),
        migrations.AddField(
            model_name='form',
            name='objective',
            field=models.TextField(default='Write here'),
        ),
        migrations.AddField(
            model_name='form',
            name='place',
            field=models.CharField(default='Write here', max_length=200),
        ),
        migrations.AddField(
            model_name='form',
            name='sdg',
            field=models.CharField(default='Write here', max_length=200),
        ),
        migrations.AddField(
            model_name='form',
            name='why',
            field=models.TextField(default='Write here'),
        ),
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(default='Write here', max_length=200),
        ),
        migrations.AlterField(
            model_name='site',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 6, 12, 32, 9, 234732), verbose_name='published date'),
        ),
    ]
