# Generated by Django 3.0.4 on 2020-03-06 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200306_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='Key_result_1',
            field=models.TextField(default='Write here'),
        ),
        migrations.AddField(
            model_name='form',
            name='Key_result_2',
            field=models.TextField(default='Write here'),
        ),
        migrations.AddField(
            model_name='form',
            name='Key_result_3',
            field=models.TextField(default='Write here'),
        ),
        migrations.AddField(
            model_name='form',
            name='Key_result_4',
            field=models.TextField(default='Write here'),
        ),
        migrations.AlterField(
            model_name='form',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 6, 12, 39, 34, 277872), verbose_name='published date'),
        ),
        migrations.AlterField(
            model_name='site',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 6, 12, 39, 34, 277872), verbose_name='published date'),
        ),
    ]
