# Generated by Django 3.0.4 on 2020-03-06 05:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200306_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('role', models.CharField(max_length=100)),
                ('birth_data', models.DateTimeField(default=datetime.datetime(2020, 3, 6, 13, 15, 53, 486202), verbose_name='Birth data')),
                ('school', models.CharField(max_length=100, verbose_name='Organisation/School')),
                ('job', models.CharField(max_length=100, verbose_name='Job Function/Major')),
            ],
        ),
        migrations.RemoveField(
            model_name='series',
            name='category',
        ),
        migrations.RemoveField(
            model_name='site',
            name='series',
        ),
        migrations.AlterField(
            model_name='form',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 6, 13, 15, 53, 486202), verbose_name='published date'),
        ),
        migrations.AlterField(
            model_name='site',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 6, 13, 15, 53, 485204), verbose_name='published date'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Series',
        ),
    ]
